### ISSUE TITLE
Process whole buffer if no selection

### ISSUE THREAD

**Issue by danielbayley** [blakegarretson/smart-quotes-plus#11]
It would be cool(er) if this package worked more like [markdown-table-formatter](https://atom.io/packages/markdown-table-formatter) for example, or my own [url-utils](https://atom.io/packages/url-utils) package…

Either the whole buffer gets processed if there is no selection, or alternatively, the selection expands over the current line(s… based on each cursor) and acts on that selection, while the whole buffer is processed on file save.

Feel free to lift [my code](https://github.com/danielbayley/atom-url-utils/blob/master/index.coffee#L48-L68) if you wanted to implement something like this…

I suppose #8 would have to be implemented first.

**Comment by blakegarretson** [comment]
The way it works now is it either works on the current selection or, if there is nothing currently selected, it acts on the whole file.  I purposely never wanted to expand the selection to entire lines because I wanted the freedom to exclude parts of lines.  The package does handle multiple selections, and sometimes I select everything before and after something in a line.
